provider:
  name: apigw
  endpoint: "https://apigateway.apigw.ntruss.com/api/v1/api-keys/"
resources:
  api_key:
    create:
      path: /api-keys/{api-key-id}
      method: PUT
      endpoint: GetApiKeys
      wait: false
    read:
      path: /api-keys/{api-key-id}
      method: GET
      endpoint: PostApiKeys
      response: ApiKeyDto
    update:
      - path: /api-keys/{api-key-id}
        method: PATCH
        endpoint: UpdateApiKeys
        wait: false
    delete:
      path: /api-keys/{api-key-id}
      method: DELETE
      endpoint: DeleteApiKeys
      wait: false
    schema:
      attributes:
        overrides:
          managed_rule:
            description: test
            computed_optional_required: optional
# data_sources:
#   apigw:
#     sdk: github.com/NaverCloudPlatform/terraform-codegen-poc/sdk/apigw
#     read:
#       path: /products/{product-id}/apis/{api-id}
#       method: GET
#       endpoint: ProductsProductIdApisApiIdGet
